apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app: backend
spec:
  type: LoadBalancer
  ports:
    # service port in cluster
  - port: 5000
    # port to contact inside container
    targetPort: 5000
  selector:
    app: backend
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: #image:latest #:version
        imagePullPolicy: Always 
        ports:
        - containerPort: 5000
      restartPolicy: Always