apiVersion: v1
kind: Service
metadata:
  name: backend2
  labels:
    app: backend2
spec:
  # type: LoadBalancer
  ports:
    # service port in cluster
  - port: 6000
    # port to contact inside container
    targetPort: 6000
  selector:
    app: backend2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend2
  labels:
    app: backend2
spec:
  replicas: 2
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: backend2
  template:
    metadata:
      labels:
        app: backend2
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: backend2
        image: phpunch/comment_kube_backend2
        imagePullPolicy: Always 
        ports:
        - containerPort: 6000
      restartPolicy: Always