apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    app: db
spec:
  type: LoadBalancer
  ports:
    # service port in cluster
  - port: 27017
    # port to contact inside container
    targetPort: 27017
  selector:
    app: db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  labels:
    app: db
spec:
  replicas: 2
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: db
        image: apcheamitru/arm32v7-mongo
        imagePullPolicy: Always
        ports:
        - containerPort: 27017
      restartPolicy: Always