apiVersion: v1
kind: Service
metadata:
  name: logging
  labels:
    app: logging
spec:
  # type: LoadBalancer
  ports:
    # service port in cluster
  - port: 8787
    # port to contact inside container
    targetPort: 8787
  selector:
    app: logging
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: logging
  labels:
    app: logging
spec:
  replicas: 2
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: logging
  template:
    metadata:
      labels:
        app: logging
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: logging
        image: saranpat/comment_kube_logging
        imagePullPolicy: Always 
        ports:
        - containerPort: 8787
      restartPolicy: Always