apiVersion: v1
kind: Service
metadata:
  name: log
  labels:
    app: log
spec:
  # type: LoadBalancer
  ports:
    # service port in cluster
  - port: 8787
    # port to contact inside container
    targetPort: 8787
  selector:
    app: log
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: log
  labels:
    app: log
spec:
  replicas: 2
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: log
  template:
    metadata:
      labels:
        app: log
    spec:
      containers:
      - name: log
        image: saranpat/comment_kube_logging
        imagePullPolicy: Always 
        ports:
        - containerPort: 8787
      restartPolicy: Always