version: "3.0"

services:
  db:
    image: mongo
    ports:
      - "27017:27017"
  #  log:
  #    ports:
  #      - "8787:8787"

  backend:
    depends_on:
      - db
      #- logging
    build: backend
    ports:
      - "5000:5000"
    #links: -logging
    restart: always

  backend2:
    depends_on:
      - db
      #- logging
    build: backend2
    ports:
      - "6000:6000"
    #links: -logging
    restart: always

  logging:
    build: logging
    ports:
      - "8787:8787"
    restart: always

  frontend:
    depends_on:
      - backend
      - backend2
    build: frontend
    ports:
      - "3000:3000"
    links:
      - backend
      - backend2
    restart: always
