apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  type: NodePort 
  ports:
    # service port in cluster
  - port: 3000
    # port to contact inside container
    nodePort: 31001
  selector:
    app: frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 2
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: iamsirid/comment_kube-frontend
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
          - name: API_ENDPOINT
            value: backend
      restartPolicy: Always

