name: Docker Buildx CI

on: 
  push:
    branches:    
      - master         # Push events on master branch

jobs:
  Buildx:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Docker Buildx
      uses: crazy-max/ghaction-docker-buildx@v1.0.4  
    - name: Run Buildx for Backend
      run: |
        docker buildx build \
          --platform linux/arm/v7 \
          --tag phpunch/comment_kube_backend \
          --file ./backend/Dockerfile ./backend
        echo finished build Backend
        docker image ls
    - name: Run Buildx for Backend2
      run: |
        docker buildx build \
          --platform linux/arm/v7 \
          --tag phpunch/comment_kube_backend2 \
          --file ./backend2/Dockerfile ./backend2
        echo finished build Backend2
        docker image ls
    - name: Run Buildx for frontend
      run: |
        docker buildx build \
          --platform linux/arm/v7 \
          --tag phpunch/comment_kube_frontend \
          --file ./frontend/Dockerfile ./frontend
        echo finished build frontend
        docker image ls
    - name: Run Buildx for logging
      run: |
        docker buildx build \
          --platform linux/arm/v7 \
          --tag phpunch/comment_kube_logging \
          --file ./logging/Dockerfile ./logging
        echo finished build Logging
        docker image ls
    - name: Publish to comment_kube_backend Docker Hub Registry
      uses: elgohr/Publish-Docker-Github-Action@2.9
      with:
        name: phpunch/comment_kube_backend
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Publish to comment_kube_backend2 Docker Hub Registry
      uses: elgohr/Publish-Docker-Github-Action@2.9
      with:
        name: phpunch/comment_kube_backend2
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Publish to comment_kube_frontend Docker Hub Registry
      uses: elgohr/Publish-Docker-Github-Action@2.9
      with:
        name: phpunch/comment_kube_frontend
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Publish to comment_kube_logging Docker Hub Registry
      uses: elgohr/Publish-Docker-Github-Action@2.9
      with:
        name: phpunch/comment_kube_logging
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

