name: Docker Buildx CI

on: 
  push:
    branches:    
      - master         # Push events on master branch

jobs:
  Buildx:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Docker Buildx
      uses: crazy-max/ghaction-docker-buildx@v1.0.4  
    - name: Run Buildx for Backend
      run: |
        docker buildx build \
          --platform linux/arm/v7 \
          -t ${{ secrets.DOCKER_REPO_NAME_BACKEND }} \
          --output "type=image,push=false" \
          --file ./backend/Dockerfile ./backend
    - name: Run Buildx for Backend2
      run: |
        docker buildx build \
          --platform linux/arm/v7 \
          -t ${{ secrets.DOCKER_REPO_NAME_BACKEND2 }} \
          --output "type=image,push=false" \
          --file ./backend2/Dockerfile ./backend2
    - name: Run Buildx for frontend
      run: |
        docker buildx build \
          --platform linux/arm/v7 \
          -t ${{ secrets.DOCKER_REPO_NAME_FRONTEND }} \
          --output "type=image,push=false" \
          --file ./frontend/Dockerfile ./frontend
    - name: Run Buildx for logging
      run: |
        docker buildx build \
          --platform linux/arm/v7 \
          -t ${{ secrets.DOCKER_REPO_NAME_LOGGING }} \
          --output "type=image,push=false" \
          --file ./logging/Dockerfile ./logging
    - name: Publish to comment_kube_backend Docker Hub Registry
      uses: elgohr/Publish-Docker-Github-Action@2.9
      with:
        name: ${{ secrets.DOCKER_REPO_NAME_BACKEND }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Publish to comment_kube_backend2 Docker Hub Registry
      uses: elgohr/Publish-Docker-Github-Action@2.9
      with:
        name: ${{ secrets.DOCKER_REPO_NAME_BACKEND2 }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Publish to comment_kube_frontend Docker Hub Registry
      uses: elgohr/Publish-Docker-Github-Action@2.9
      with:
        name: ${{ secrets.DOCKER_REPO_NAME_FRONTEND }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Publish to comment_kube_logging Docker Hub Registry
      uses: elgohr/Publish-Docker-Github-Action@2.9
      with:
        name: ${{ secrets.DOCKER_REPO_NAME_LOGGING }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

